# Metereologia CDMX

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('meteorologia_N6//meteorología_2025.csv')

In [3]:
data = data.dropna()

In [4]:
data.head()

                  date id_station id_parameter  valor  unit
0  2025-01-01 00:00:00        ACO          TMP    8.7     5
1  2025-01-01 00:00:00        ACO           RH   28.0     6
2  2025-01-01 00:00:00        ACO          WSP    2.4     3
3  2025-01-01 00:00:00        ACO          WDR    2.0     4
4  2025-01-01 00:00:00        AJM          TMP    9.6     5

In [5]:
data['id_station'].groupby(data['id_station']).count().sort_values(ascending=False)

id_station
UAX    35028
MER    34970
CUT    34944
AJM    34933
MGH    34927
PED    34743
NEZ    29690
GAM    28151
UIZ    28108
INN    26771
VIF    26106
LAA    26061
SAG    25629
FAC    24999
MPA    24837
MON    23495
TAH    23313
CHO    23295
BJU    23241
FAR    22441
CUA    22440
ACO    19968
SAC    17947
AJU     3037
Name: id_station, dtype: int64

La estacion con la que vamos a trabajar es UAX, es la que mas valores tiene.

In [6]:
df = data[(data['id_station'] == 'UAX')]

Hacemos una tabla donde cada columna sea el ambiente en filas ordenadas por el tiempo en el que se tomó.

In [7]:
df_piv = df.pivot(index='date', columns='id_parameter', values='valor')
df_piv.head()

id_parameter           RH   TMP    WDR  WSP
date
2025-01-01 00:00:00  41.0  13.3  231.0  1.1
2025-01-01 01:00:00  45.0  12.1  193.0  1.1
2025-01-01 02:00:00  46.0  11.2  199.0  1.0
2025-01-01 03:00:00  55.0   9.9   18.0  0.2
2025-01-01 04:00:00  55.0   9.3  145.0  1.1

a) Probabilidad de humedad alta >= 70 (RH)

In [8]:
p_hum_alta = (df_piv['RH'] >= 70).mean()
p_hum_alta

np.float64(0.35834189791024323)

b) Probabilidad de viento tranquilo <= 1 (WSP)

In [9]:
p_viento_tranq = (df_piv['WSP'] <= 1).mean()
p_viento_tranq

np.float64(0.22130866735183283)

c) P(hum. alta | viento tranquilo)

In [10]:
p_hum_dado_viento = (df_piv[df_piv['WSP'] <= 1]['RH'] >= 70).mean()
p_hum_dado_viento

np.float64(0.673890608875129)

d) P(viento tranq | hum. alta)

In [11]:
p_viento_dado_hum = (df_piv[df_piv['RH'] >= 70]['WSP'] <= 1).mean()
p_viento_dado_hum

np.float64(0.41618865519439135)